# CircuitSetup 6 Channel Energy Meter ESPHome common variables
# using the Lilygo T-ETH-Lite ESP32S3 and the CircuitSetup 6 Channel Energy Meter Ethernet Adapter 

esphome:
  name: "${disp_name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  min_version: '2025.5.0'
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: circuitsetup.6c-energy-meter-ethernet
    version: "1.5"

esp32:
  board: esp32-s3-devkitc-1
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

captive_portal:

improv_serial:

# Enable logging
logger:
  level: DEBUG

debug:
  update_interval: 5s

# Enable Home Assistant API
api:

ota:
  - platform: esphome

ethernet:
  type: W5500
  clk_pin: 10
  mosi_pin: 12
  miso_pin: 11
  cs_pin: 9
  interrupt_pin: 13
  reset_pin: 14
  clock_speed: 30Mhz

spi:
  interface: software
  clk_pin: 7
  miso_pin: 5
  mosi_pin: 6

switch:
  - platform: restart
    name: ${disp_name} Restart

time:
  - platform: homeassistant
    id: homeassistant_time
